.prettierrc
package-lock.json
package.json
src/App.jsx
src/components/ColoredBorder.jsx
src/components/DateInput.jsx
src/components/FormInputButtons.jsx
src/components/InfoGerais.jsx
src/components/Navbar.jsx
src/components/ProfileForm.jsx
src/components/RadioButtonInput.jsx
src/components/Sidebar.jsx
src/components/SimpleTextInput.jsx
src/components/TimeInput.jsx
src/index.jsx
src/pages/EndProtocolPage.jsx
src/pages/ProfilePage.jsx
src/pages/SplashPage.jsx
src/pages/TermsPage.jsx
src/reportWebVitals.js

- Adicionado Prettier como dependência de desenvolvimento;
- Adicionado arquivo de configurações padrão para o Prettier e script de execução;
- Indentação geral dos arquivos do repositório padronizada;
**Em caso de uso de outra forma de indentação, convém seguir as configurações definidas no .prettierrc;**
**Comando para aplicar as alterações de acordo com as configurações definidas:**
`npm run prettier`

34 padronizar configurações de indentação

---

src/App.jsx
src/components/Weather.jsx

- Em App.jsx eu apenas corrigi o import de DateInput e TimeInput;
- Em Weather.jsx eu alinhei o botão de input com a descrição/textinho da alternativa e retirei a margem top do primeiro;

[FIX] correções em App.jsx e em Weather.jsx

---

src/App.jsx
src/pages/AboutPage.jsx

- Página AboutPage "Sobre o aplicativo";
- Código basicamente idêntico à TermsPage: levar em consideração possibilidade de mesclar ambas no futuro (mais atualizações de componente e menos redirecionamentos);

41 pagina sobre app

---

src/App.jsx
src/components/Location.jsx
src/components/Navbar.jsx
src/components/Weather.jsx
src/pages/EndProtocolPage.jsx
src/pages/ProfilePage.jsx
src/pages/TermsPage.jsx

- Componente NavBar de acordo com novo leiaute submetido no Figma: sem logo e com toggle à esquerda;

4 componente navbar atualizado segundo novo leiaute

---

src/App.jsx
src/pages/HelpPage.jsx

- Página que deve aparecer quando o usuário clica no botão de ajuda;
- Nenhuma observação;

18 página ajuda app

---

src/App.jsx
src/components/ColoredBorder.jsx
src/components/DateInput.jsx
src/components/FormInputButtons.jsx
src/components/HomeArrows.jsx
src/components/HomeButton.jsx
src/components/HomeButtonList.jsx
src/components/InfoGerais.jsx
src/components/Location.jsx
src/components/Navbar.jsx
src/components/ProfileForm.jsx
src/components/ProtocolOptions.jsx
src/components/RadioButtonInput.jsx
src/components/Sidebar.jsx
src/components/SimpleTextInput.jsx
src/components/TimeInput.jsx
src/components/Weather.jsx
src/pages/AboutPage.jsx
src/pages/EndProtocolPage.jsx
src/pages/HelpPage.jsx
src/pages/HomePage.jsx
src/pages/ProfilePage.jsx
src/pages/ProtocolPage.jsx
src/pages/SplashPage.jsx
src/pages/TermsPage.jsx

50 retirar elementos não utilizados

---

src/App.jsx
src/components/DateInput.jsx
src/components/FormInputButtons.jsx
src/components/HomeButtonList.jsx
src/components/InfoGerais.jsx
src/components/Location.jsx
src/components/RadioButtonInput.jsx
src/components/Sidebar.jsx
src/components/SimpleTextInput.jsx
src/components/TimeInput.jsx
src/components/Weather.jsx
src/pages/EndProtocolPage.jsx
src/pages/HomePage.jsx
src/pages/LoginPage.jsx
src/pages/ProtocolPage.jsx

- Favor verificar com atenção todas as modificações;

[FIX] rotas e estilizações

---

src/components/Navbar.jsx

- A navBar agora recebe uma prop booleana informando se o botão de toggle para sideBar deve ou não ser exibido, vide o mesmo não ser comum à todas às páginas da dashboard;
- Pequenas refatorações no componente;

91 add componente navbar dashboard

---

src/pages/SplashPage.jsx

- Apenas refatoração de código e alteração de tamanhos;
- A página já era responsiva;

5 página de carregamento - dashboard

---

src/App.jsx
src/components/RecoveryAlert.jsx
src/pages/AlertsPage.jsx

Não consegui mexer no padding do botão "OK" porque ele faz parte de outro componente.

[ADD] Componente alerta de recuperação de senha

---

src/App.jsx

- Correção de erro que passou na PR #111;
- Importação do Bootstrap estava divergente e resultando em funções duplicadas;

110 fix substituir cdns por dependências

---

src/components/Sidebar.jsx
src/pages/ProfilePage.jsx

**Substituição de anchor e correções na ProfilePage**
- Só haviam anchors funcionais na Sidebar, todos os outros são "falsos links" que não levam à lugar nenhum;
- ProfilePage com declarações faltantes e Sidebar sem Modal;

#132/#71 [REFACTOR]: Substituir componentes anchor por link e correção na ProfilePage

---

src/pages/AnswerPage.jsx
src/pages/InfosPage.jsx

**Página de visualização de respostas e correções em InfosPage**
- InfosPage corrigida para se aproximar das convenções adotadas em outras páginas;
- AnswerPage refeita à partir do leiaute no Figma;
- Não ficou claro pra mim o que deveria ser feito com as questões de seleção única/múltipla discutidas em reunião: por ora mantive o leiaute igual ao das questões textuais;
- A API aparentemente não informa quem respondeu às perguntas;
- O leiaute proposto não permitia escolher a visualização: por ora mantive a escolha em links;

#139/#94 [FEAT]: Página de visualização de respostas e correções em InfosPage

---

src/pages/ProtocolPage.jsx

- Alterei a estilização do botão de enviar;
- Removi o outline do input do nome porque ao meu ver não estava muito elegante, nada d+;

#67 [refactor]: botão de enviar + outline input

---

src/pages/ProtocolPage.jsx
src/utils/constants.jsx

**InfoGerais removido dos campos obrigatórios implícitos**
- Alterações em AnswerPage ignoradas vide página defasada;

#144 [REFACTOR]: Remover componente InfoGerais dos campos obrigatórios implícitos

---

src/pages/LoginPage.jsx

- deixei comentado vide possível reutilização desse código em uma versão definitiva

[FIX] remocao criar conta

---

src/pages/ProtocolPage.jsx

Mudei o texto ao enviar o protocolo de acordo com o que está no Figma :)

#179 [REFACTOR]: atualizar pop-up de resposta protocolo

---

src/components/inputs/answers/SelectInput.jsx
src/pages/ProtocolPage.jsx

#126 [FIX] Componente lista suspensa

---

src/components/Sidebar.jsx
src/pages/InfosPage.jsx
src/pages/ProfilePage.jsx

- Acabei optando por simplesmente remover o "to" do Link que redirecionava para o site de denúncias, por hora creio eu que seja uma solução... Se alguém achar melhor tirar ou colocar outro link, é tranquilo de corrigir também :)
- Aproveitei e corrigi da forma como deu o display nas páginas em que a sidebar é estática;

#191 [FIX]: fixes the display and removes the reporting site link

---

src/components/Sidebar.jsx
src/pages/CreateProtocolPage.jsx
src/pages/HomePage.jsx
src/pages/ProtocolPage.jsx

- Apenas retirei essa class: "d-lg-none" da div do botão de fechar a sidebar, pois a mesma é responsável por remover o elemento em grandes telas, não entendi o motivo de ter sido implementado dessa forma pra ser sincero kkkkkkk

[FIX] botão de fechar da sidebar dinâmico em todas as resoluções

---

src/components/inputs/protocol/CreateMultipleInputItens.jsx
src/pages/CreateProtocolPage.jsx

- Acabei adicionando também pra parte de lista suspensa;
- Não sei se eh a melhor forma de fazer, mas apenas reaproveitei o que havíamos feito com o componente de Seleção Única e tornei ele dinâmico para receber títulos diferentes :-);

[REFACTOR]: componente de criar itens com vários inputs 

---

src/contexts/AuthContext.js
src/pages/InfosPage.jsx
src/routes/AppRoutes.jsx
src/utils/constants.jsx

- Está faltando a questão do usuário aceitar os termos de uso uma única vez :(
- obs: se alguém tiver alguma solução estou aceitando;

210 fix página de termos app

---

src/pages/InfosPage.jsx

- Corrigi o alinhamento do texto;
- Removi o botão de ajuda.

[FIX]: correção do texto alinhado à esquerda e remoção do botão de ajuda

---

src/components/inputs/answers/ImageInput.jsx

- Obs: eu acabei substituindo o fundo cinza pela borda preta, fiz isso por conta do botão de remoção, já que assim o usuário consegue ter uma noção de qual componente o mesmo estará removendo, ou seja, foi proposital hehe...

220 fix componente image input

---

src/pages/HomePage.jsx

- Fui testar e percebi que o botão de logout da sidebar não estava funcionando por conta disso :D

[FIX]: add Alert component and the ref attribute to reference the modal

---

src/pages/LoginPage.jsx
src/routes/AppRoutes.jsx

Feito senhores, única coisa que reparei é que a SignUpPage tá inacessível, de qualquer forma, o link pra ela tá ali

#229 [ADD]: link to signup added (web version)

---

src/pages/CreateProtocolPage.jsx

não sei se fiz certo, adicionei um campo igual o de título/descrição para a data de publicação e fiz uma funçãozinha para verificar qual a rota e mostrar os botões com base nisso (acredito que é pra esconder quando está criando e mostrar quando está editando né?). Por algum motivo deu que eu deletei e adicionei um monte de coisa no código, mas tá quase tudo igual

#232 [FIX]: added date field and conditional check for buttons appearance

---

src/components/inputs/answers/SelectInput.jsx

- Componente renderizava corretamente com exemplos fornecidos em PRs anteriores, mas a API não retorna objetos neste formato, inviabilizando o uso;
- Ressalta-se a necessidade de desenvolver as funções relacionadas ao funcionamento do componente, que aparenta ser apenas visual por ora;

[FIX]: Renderização de opções com propriedades errôneas em SelectionInput

---

src/components/inputs/answers/CheckBoxInput.jsx
src/components/inputs/answers/RadioButtonInput.jsx
src/components/inputs/answers/SelectInput.jsx
src/components/inputs/answers/SimpleTextInput.jsx
src/pages/ProtocolPage.jsx

**Funcionalidades implementadas**
- Renderização de itens de seleção única, seleção múltipla, lista suspensa e caixa de texto conforme nova API;
- Acesso autenticado com logout automático em caso de erro de autenticação;
- Respostas NÃO funcionando atualmente. Devido à grande diferença entra a formatação das respostas e complexidade da issue, acredito que talvez seja mais viável dividí-la em issues menores;
- Os campos alterados são a interseção do que é suportado pela nova API e pelo front no momento. Itens cujo tipo é suportado por apenas um, foram removidos, cabendo reinserção conforme alinhamento;
- Desviada da #247, a qual sugiro que seja revisada antes;

#249 [FEAT]: Compatibilização de rota de visualização de protocolos com nova API

---

package-lock.json
package.json
src/components/Alert.jsx
src/components/ProtocolCarousel.jsx
src/components/inputs/answers/CheckBoxInput.jsx
src/components/inputs/answers/RadioButtonInput.jsx
src/components/inputs/answers/SelectInput.jsx
src/components/inputs/answers/SimpleTextInput.jsx
src/contexts/AuthContext.js
src/pages/HomePage.jsx
src/pages/LoginPage.jsx
src/pages/ProtocolPage.jsx

**Correções realizadas**
- Eventos assíncronos do modal Alert se sobrepondo ao realizar chamadas encadeadas do mesmo modal via hook useRef;
**Funcionalidades adicionadas**
- Propriedade dismissible visando permitir alertas persistentes (que não possuem botão de fechar);
- Utilização do alerta persistente para evitar que o usuário interrompa o processamento de uma resposta;

#251 [FIX/FEAT]: Correção e aprimoramento do uso de alertas na página de resposta de protocolos

---

package-lock.json
package.json
src/components/Alert.jsx
src/components/ProtocolCarousel.jsx
src/components/inputs/answers/CheckBoxInput.jsx
src/components/inputs/answers/DateInput.jsx
src/components/inputs/answers/ImageInput.jsx
src/components/inputs/answers/LocationInput.jsx
src/components/inputs/answers/RadioButtonInput.jsx
src/components/inputs/answers/SelectInput.jsx
src/components/inputs/answers/SimpleTextInput.jsx
src/components/inputs/answers/TextImageInput.jsx
src/components/inputs/answers/TimeInput.jsx
src/contexts/AuthContext.js
src/pages/HomePage.jsx
src/pages/LoginPage.jsx
src/pages/ProtocolPage.jsx

**Correções adicionadas**
- Suporte à visualização de itens dos tipos TIMEBOX, DATEBOX, LOCATIONBOX, UPLOAD, TEXT;
- Suporte à visualização de imagens ainda pendente conforme protocolos na nova API não foram criados com imagens;
- Upload de imagens ainda não suportado;
- Desviada da #251;

#253 [FIX] Compatibilização de tipos de item faltantes em página de resposta de aplicação

---

package-lock.json
package.json
src/App.jsx
src/components/Alert.jsx
src/components/ProtocolCarousel.jsx
src/components/inputs/answers/CheckBoxInput.jsx
src/components/inputs/answers/DateInput.jsx
src/components/inputs/answers/ImageInput.jsx
src/components/inputs/answers/LocationInput.jsx
src/components/inputs/answers/RadioButtonInput.jsx
src/components/inputs/answers/SelectInput.jsx
src/components/inputs/answers/SimpleTextInput.jsx
src/components/inputs/answers/TextImageInput.jsx
src/components/inputs/answers/TimeInput.jsx
src/contexts/AuthContext.js
src/contexts/StorageContext.js
src/pages/HomePage.jsx
src/pages/LoginPage.jsx
src/pages/ProtocolPage.jsx

**Funcionalidades adicionadas**
- StorageContext com detecção de conexão/desconexão;
- Armazenamento de protocolo atual e requisições pendentes em StorageContext e localStorage;
- Alerta de desconexão durante resposta de protocolo;
- Alerta de requisição pendente após tentativa de resposta em modo offline;
- Desviada da #255;
- Discutível se localStorage é o local mais apropriado para estes armazenamentos;
- Guarda o protocolo atual no contexto, mas não o utiliza por ora;
- Não há necessidade de manter-se na página para que a resposta seja submetida;
- Conversão de JSON/FormData necessária para localStorage vide não serem serializáveis entre si e o pacote de conversão atual ter propósito diferente;
- Escopo da issue alterada vide não tratar-se de modo online completo;

#257 [FEAT]: Suporte à respostas offline

---

src/pages/AnswerPage.jsx

Mudei algumas coisas pra ficar mais parecido com o figma e verifiquei a responsividade.

#233 [FIX]: changed AswerPage.jsx to be more like the project on figma

---

src/components/inputs/protocol/CreateMultipleInputItens.jsx
src/components/inputs/protocol/CreateTextBoxInput.jsx
src/pages/CreateProtocolPage.jsx
src/utils/constants.jsx

**Correções adicionadas**
- Função central (a que a página utiliza para armazenar o conjunto de itens e envia para que os componentes os editem) atualizada conforme formato da nova API, implicando na alteração de constantes, das  funções de adição, edição e remoção de itens, da função de submissão de protocolo, tal como outras refatorações;
- Removidas, por ora, as funções atribuídas à página de edição de protocolo (que usa os mesmos componentes), a qual deve ser atualizada e reinserida em issue futura;
- Removida constante de protocolos padrão vide defasagem;
- Removidas checagem de validações vide não haver suporte na API no momento;
- Os itens são criados em uma página única e em um grupo único, vide  não haver leiaute para paginação por ora;

#269 [FIX]: Adaptação da função central da dashboard para nova API

---

src/components/inputs/protocol/CreateMultipleInputItens.jsx
src/components/inputs/protocol/CreateTextBoxInput.jsx
src/pages/CreateProtocolPage.jsx
src/utils/constants.jsx

**Funcionalidades adicionadas**
- Adaptação da criação de itens textuais via dashboard para nova API;

#270 [FIX]: Adaptação da criação de itens textuais via dashboard para nova API

---

src/components/inputs/protocol/CreateMultipleInputItens.jsx
src/components/inputs/protocol/CreateTextBoxInput.jsx
src/pages/CreateProtocolPage.jsx
src/utils/constants.jsx

**Funcionalidades adicionadas**
- Adaptada criação de itens com opções para nova API (seleção única, múltipla escolha e lista suspensa);
- Partes que envolvem a edição de protocolos criados e validações (sem suporte na API) removidas por ora para suporte em issue posterior;

#271 [FIX]: Adaptação da criação de itens com opções via dashboard para nova API

---

src/components/inputs/answers/SimpleTextInput.jsx
src/pages/ProtocolPage.jsx

Fiz uma verificação se o item.type é number ou text pra mudar o input type;
manos uma dúvida só, não consegui achar no nosso código onde essa propriedade item é declarada e nem quais os possíveis valores que são disponíveis para item.type, possível que tenha algum erro de concordância no nome dos valores, pode ser que funcione também, se alguém conseguir verificar pra mim eu agradeço!

#282[FIX]: simpleTextInput changes type to number according to item.type

---

src/components/GalleryModal.jsx

#397 [FEAT]: Suporte a exibição de descrição e correções gerais no modal Galeria

---

src/pages/CreateClassroomPage.jsx

#399 [FEAT]: Leiaute da página de criação de salas de aula

---

src/components/CreateProcotolProperties.jsx
src/components/HomeButton.jsx
src/components/Sidebar.jsx
src/contexts/AlertContext.jsx
src/contexts/LayoutContext.js
src/pages/AnswerPage.jsx
src/pages/ApplicationPage.jsx
src/pages/ApplicationsPage.jsx
src/pages/CreateApplicationPage.jsx
src/pages/CreateClassroomPage.jsx
src/pages/CreateInstitutionPage.jsx
src/pages/CreateProtocolPage.jsx
src/pages/CreateUserPage.jsx
src/pages/InstitutionsPage.jsx
src/pages/ProtocolsPage.jsx
src/pages/SignInPage.jsx
src/pages/SignUpPage.jsx

This pull request focuses on standardizing the `showAlert` function across various components by updating its parameters and improving code consistency. The changes mainly involve renaming properties and simplifying the alert configurations.
* [`src/components/CreateProcotolProperties.jsx`](diffhunk://#diff-899404c87997e4e0edf272452c29901e6447cb5449efdb8deedf4e970da70e81L83-R83): Updated `showAlert` calls to use `headerText` and `bodyText` instead of `title` and `description`. [[1]](diffhunk://#diff-899404c87997e4e0edf272452c29901e6447cb5449efdb8deedf4e970da70e81L83-R83) [[2]](diffhunk://#diff-899404c87997e4e0edf272452c29901e6447cb5449efdb8deedf4e970da70e81L130-R122)
* [`src/components/HomeButton.jsx`](diffhunk://#diff-fce0bc8731e01df17ebf6cd4141dca5861d5a88ed218e22c9e45fa872ec1a8ccL84-R89 …

#453 [FIX]: Correção de propriedades padrão em alertas

---

config-overrides.js
package.json
src/pages/CreateUserPage.jsx
src/pages/ProfilePage.jsx
src/pages/SignInPage.jsx

Esse pull request inclui várias atualizações para melhorar a segurança e o processo de compilação do projeto. As principais alterações envolvem a adição de novas dependências, a modificação de scripts de compilação e o aprimoramento da funcionalidade de login.
* Adição do `crypto-browserify` ao `config.resolve.fallback` em `config-overrides.js` para garantir a compatibilidade com o ambiente do navegador. 
* Atualização do `package.json` para incluir novas dependências: `@babel/plugin-proposal-private-property-in-object`, `bcryptjs`, `crypto-browserify`, and `@types/bcryptjs`. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R6-R15) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R55-R58)
* Substituição de …

#460 [FIX]: Criptografia das senhas em endpoints de autenticação

---

src/components/CustomContainer.jsx
src/pages/ErrorPage.jsx
src/pages/SplashPage.jsx

Esse pull request inclui atualizações no componente `ErrorPage` em `src/pages/ErrorPage.jsx` para melhorar o layout e o estilo da página de erro. As alterações mais importantes envolvem ajustes nos estilos CSS e modificações na estrutura dos elementos JSX.
* [`src/pages/ErrorPage.jsx`](diffhunk://#diff-1db987029d0c318ae80192bb45129c35f2f3f754655d70e329f00c3a320e2b31L24-R29): Atualizados os estilos `.logo-picce-circular` e `.logo-picce-textual` para ajustar suas propriedades de largura a fim de melhorar a consistência visual.
* [`src/pages/ErrorPage.jsx`](diffhunk://#diff-1db987029d0c318ae80192bb45129c35f2f3f754655d70e329f00c3a320e2b31L50-R66): Refatoração da estrutura JSX dentro da função `ErrorPage` para melhorar o alinhamento e o espaçamento dos elementos. Isso inclui alterações no …

#455 [FIX]: Responsividade da página de erro

---

src/components/inputs/answers/RangeInput.jsx
src/pages/AnswerPage.jsx
src/pages/ApplicationPage.jsx

This pull request includes several changes to the `src/pages/AnswerPage.jsx` and `src/components/inputs/answers/RangeInput.jsx` files to improve the handling of user inputs and the formatting of CSV outputs. The most important changes are grouped by theme below:
* [`src/components/inputs/answers/RangeInput.jsx`](diffhunk://#diff-a51c31f7ebabc1c5b5fe98c9e9df4a041d9ba312e2c2f999c5f3c2a2845f90e3L102-R102): Updated the `value` attribute to default to `min` if `parseFloat(answer.text)` is falsy.
* [`src/pages/AnswerPage.jsx`](diffhunk://#diff-847e3332d792c3f737bbded8e810b6a4db1e597a2fbd6eb1ba43a3fc9c940118L249-R269): Enhanced the handling of 'UPLOAD' type answers by processing and filtering uploaded files to include only image files, and generating the appropriate URLs.
* …

#501 [FIX]: Delimitador e condicional para exportar imagens atualizados

---

src/components/ProtocolList.jsx
src/components/RoundedButton.jsx
src/components/inputs/answers/TableInput.jsx
src/pages/ApplicationAnswersPage.jsx
src/pages/ApplicationPage.jsx
src/pages/ApplicationsPage.jsx
src/pages/InstitutionPage.jsx
src/pages/InstitutionsPage.jsx
src/pages/ProtocolAnswersPage.jsx
src/pages/ProtocolPage.jsx
src/pages/ProtocolsPage.jsx
src/routes/AppRoutes.jsx

Esta solicitação de pull inclui várias atualizações para `RoundedButton`, `TableInput` e várias páginas dentro do aplicativo. As alterações se concentram principalmente em adicionar novas propriedades, refatorar o código existente e atualizar rotas para melhorar a funcionalidade e a manutenibilidade do aplicativo.
* Removido o sinalizador `!important` da propriedade `color` na função `roundedButtonStyles`.
* Adicionado suporte para o atributo `data-bs-target` no componente `RoundedButton`. [[1]](diffhunk://#diff-960af39c48728e5e9c1e966989b9cfb2c08217d97bcc7d3aaf3d40ab146f8a30R70) [[2]](diffhunk://#diff-960af39c48728e5e9c1e966989b9cfb2c08217d97bcc7d3aaf3d40ab146f8a30R81)
* Adicionada a prop `isProtocol` ao componente `TableInput`.
* Melhorada a legibilidade e a manutenibilidade do …

#499 [FEAT]: Página para visualização condensada de respostas de protocolo

---

src/App.jsx
src/components/CreateProcotolProperties.jsx
src/pages/CreateApplicationPage.jsx
src/pages/CreateProtocolPage.jsx
src/pages/InstitutionPage.jsx
src/pages/UsersPage.jsx

Listas de usuários e grupos na página de criação de protocolo agora são deslizáveis.

#521 [FEAT] Layout das listas de usuários.

---

src/components/Addbar.jsx
src/components/CreatePage.jsx
src/components/CreateProcotolProperties.jsx
src/pages/CreateProtocolPage.jsx

This pull request includes several changes to the `src/components/Addbar.jsx`, `src/components/CreatePage.jsx`, `src/components/CreateProcotolProperties.jsx`, and `src/pages/CreateProtocolPage.jsx` files. The changes primarily focus on enhancing the tooltip functionality, adding new buttons, and improving the scrollbar styles.
Enhancements to tooltips and buttons:
* [`src/components/Addbar.jsx`](diffhunk://#diff-75de2cb65a4203ff2eaf2525b880994c07bfc64de11237dad442dacdd81bd44bR71-R74): Added new tooltips for various buttons and introduced new buttons for inserting different types of tables and items. [[1]](diffhunk://#diff-75de2cb65a4203ff2eaf2525b880994c07bfc64de11237dad442dacdd81bd44bR71-R74) [[2]](diffhunk://#diff-75de2cb65a4203ff2eaf2525b880994c07bfc64de11237dad442dacdd81bd44bR130-R162) …

#532 [REF]: Ajustes nas barras de rolagem das páginas relacionadas a criação de protocolo e ajustes nos botões da addbar

---

src/App.jsx

This pull request includes a small change to the `src/App.jsx` file. The change adds custom styles for the scrollbar in the `.user-list` class to improve its appearance.
* [`src/App.jsx`](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661R32-R45): Added custom styles for the scrollbar in the `.user-list` class, including width, track background, thumb background, and hover effects.

[FEAT]: Estilos de barra de rolagem personalizados para a lista de usuários e grupos para melhor visibilidade, usabilidade e consistência

---

src/components/inputs/answers/ImageInput.jsx
src/components/inputs/answers/RangeInput.jsx
src/components/inputs/answers/SelectInput.jsx
src/components/inputs/protocol/CreateMultipleInputItens.jsx
src/components/inputs/protocol/CreateRangeInput.jsx
src/components/inputs/protocol/CreateTextBoxInput.jsx
src/pages/ApplicationAnswersPage.jsx
src/pages/ApplicationPage.jsx
src/pages/ProtocolPage.jsx

This pull request includes significant changes to the `src/components/inputs/answers` and `src/pages` directories to enhance image handling and improve the user interface. The most important changes include adding a `Gallery` component, modifying props to include `galleryModalRef`, and updating the image source paths.
Enhancements to image handling:
* [`src/components/inputs/answers/ImageInput.jsx`](diffhunk://#diff-964ba6fdbd3045ac475b7a9a743c552810a04ea6a6961927ec14cdbbd760a3c2R18): Added `Gallery` component and included `galleryModalRef` in props. Updated the image processing logic to handle file extensions and create a new `File` object with the processed image. [[1]](diffhunk://#diff-964ba6fdbd3045ac475b7a9a743c552810a04ea6a6961927ec14cdbbd760a3c2R18) …

538 fix bugs relacionados as imagens

---

src/components/CreateItemGroup.jsx
src/components/inputs/protocol/CreateValidationInput.jsx

Esta solicitação de pull inclui atualizações para o componente `CreateValidationInput` para corrigir as atualizações de estado das validações e garantir a consistência nos nomes de prop. As alterações mais importantes incluem a atualização do nome do prop de `updateValidation` para `updateItemValidation` e a correção dos parâmetros enviados em suas chamadas;
Atualizações para o componente `CreateValidationInput`:
* [`src/components/inputs/protocol/CreateValidationInput.jsx`](diffhunk://#diff-0ab8145dce8fc5c3875d456189dd14196b617c9e4a4ecf7c09d6d0158bee3c51L7-R12): O nome do prop foi alterado de `updateValidation` para `updateItemValidation` e o uso correspondente foi atualizado no componente.
* [`src/components/inputs/protocol/CreateValidationInput.jsx`](diffhunk://#diff-0ab8145dce8fc5c3875 …

#541 [FIX]: Manuseio e atualização de validações na gerência de protocolos
